//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Administracion.ServicioWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioTURUSoap", Namespace="http://tempuri.org/")]
    public partial class ServicioTURU : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarCompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarCompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarCompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarCompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCompaniasOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogueoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarTerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarTerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarTerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarTerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTerminalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback HerenciaInternacionalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback HerenciaNacionalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarViajesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViajesXMLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioTURU() {
            this.Url = global::Administracion.Properties.Settings.Default.Administracion_ServicioWeb_ServicioTURU;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarCompaniaCompletedEventHandler BuscarCompaniaCompleted;
        
        /// <remarks/>
        public event AgregarCompaniaCompletedEventHandler AgregarCompaniaCompleted;
        
        /// <remarks/>
        public event ModificarCompaniaCompletedEventHandler ModificarCompaniaCompleted;
        
        /// <remarks/>
        public event EliminarCompaniaCompletedEventHandler EliminarCompaniaCompleted;
        
        /// <remarks/>
        public event ListarCompaniasCompletedEventHandler ListarCompaniasCompleted;
        
        /// <remarks/>
        public event BuscarEmpleadoCompletedEventHandler BuscarEmpleadoCompleted;
        
        /// <remarks/>
        public event AgregarEmpleadoCompletedEventHandler AgregarEmpleadoCompleted;
        
        /// <remarks/>
        public event ModificarEmpleadoCompletedEventHandler ModificarEmpleadoCompleted;
        
        /// <remarks/>
        public event EliminarEmpleadoCompletedEventHandler EliminarEmpleadoCompleted;
        
        /// <remarks/>
        public event LogueoCompletedEventHandler LogueoCompleted;
        
        /// <remarks/>
        public event BuscarTerminalCompletedEventHandler BuscarTerminalCompleted;
        
        /// <remarks/>
        public event AgregarTerminalCompletedEventHandler AgregarTerminalCompleted;
        
        /// <remarks/>
        public event ModificarTerminalCompletedEventHandler ModificarTerminalCompleted;
        
        /// <remarks/>
        public event EliminarTerminalCompletedEventHandler EliminarTerminalCompleted;
        
        /// <remarks/>
        public event ListarTerminalesCompletedEventHandler ListarTerminalesCompleted;
        
        /// <remarks/>
        public event HerenciaInternacionalesCompletedEventHandler HerenciaInternacionalesCompleted;
        
        /// <remarks/>
        public event HerenciaNacionalesCompletedEventHandler HerenciaNacionalesCompleted;
        
        /// <remarks/>
        public event BuscarViajeCompletedEventHandler BuscarViajeCompleted;
        
        /// <remarks/>
        public event AgregarViajeCompletedEventHandler AgregarViajeCompleted;
        
        /// <remarks/>
        public event ModificarViajeCompletedEventHandler ModificarViajeCompleted;
        
        /// <remarks/>
        public event EliminarViajeCompletedEventHandler EliminarViajeCompleted;
        
        /// <remarks/>
        public event ListarViajesCompletedEventHandler ListarViajesCompleted;
        
        /// <remarks/>
        public event ViajesXMLCompletedEventHandler ViajesXMLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarCompania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Compania BuscarCompania(string nombre) {
            object[] results = this.Invoke("BuscarCompania", new object[] {
                        nombre});
            return ((Compania)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarCompaniaAsync(string nombre) {
            this.BuscarCompaniaAsync(nombre, null);
        }
        
        /// <remarks/>
        public void BuscarCompaniaAsync(string nombre, object userState) {
            if ((this.BuscarCompaniaOperationCompleted == null)) {
                this.BuscarCompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarCompaniaOperationCompleted);
            }
            this.InvokeAsync("BuscarCompania", new object[] {
                        nombre}, this.BuscarCompaniaOperationCompleted, userState);
        }
        
        private void OnBuscarCompaniaOperationCompleted(object arg) {
            if ((this.BuscarCompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarCompaniaCompleted(this, new BuscarCompaniaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarCompania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarCompania(Compania c) {
            this.Invoke("AgregarCompania", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void AgregarCompaniaAsync(Compania c) {
            this.AgregarCompaniaAsync(c, null);
        }
        
        /// <remarks/>
        public void AgregarCompaniaAsync(Compania c, object userState) {
            if ((this.AgregarCompaniaOperationCompleted == null)) {
                this.AgregarCompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarCompaniaOperationCompleted);
            }
            this.InvokeAsync("AgregarCompania", new object[] {
                        c}, this.AgregarCompaniaOperationCompleted, userState);
        }
        
        private void OnAgregarCompaniaOperationCompleted(object arg) {
            if ((this.AgregarCompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarCompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarCompania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarCompania(Compania c) {
            this.Invoke("ModificarCompania", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void ModificarCompaniaAsync(Compania c) {
            this.ModificarCompaniaAsync(c, null);
        }
        
        /// <remarks/>
        public void ModificarCompaniaAsync(Compania c, object userState) {
            if ((this.ModificarCompaniaOperationCompleted == null)) {
                this.ModificarCompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarCompaniaOperationCompleted);
            }
            this.InvokeAsync("ModificarCompania", new object[] {
                        c}, this.ModificarCompaniaOperationCompleted, userState);
        }
        
        private void OnModificarCompaniaOperationCompleted(object arg) {
            if ((this.ModificarCompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarCompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCompania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarCompania(Compania c) {
            this.Invoke("EliminarCompania", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void EliminarCompaniaAsync(Compania c) {
            this.EliminarCompaniaAsync(c, null);
        }
        
        /// <remarks/>
        public void EliminarCompaniaAsync(Compania c, object userState) {
            if ((this.EliminarCompaniaOperationCompleted == null)) {
                this.EliminarCompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarCompaniaOperationCompleted);
            }
            this.InvokeAsync("EliminarCompania", new object[] {
                        c}, this.EliminarCompaniaOperationCompleted, userState);
        }
        
        private void OnEliminarCompaniaOperationCompleted(object arg) {
            if ((this.EliminarCompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarCompanias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Compania[] ListarCompanias() {
            object[] results = this.Invoke("ListarCompanias", new object[0]);
            return ((Compania[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCompaniasAsync() {
            this.ListarCompaniasAsync(null);
        }
        
        /// <remarks/>
        public void ListarCompaniasAsync(object userState) {
            if ((this.ListarCompaniasOperationCompleted == null)) {
                this.ListarCompaniasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCompaniasOperationCompleted);
            }
            this.InvokeAsync("ListarCompanias", new object[0], this.ListarCompaniasOperationCompleted, userState);
        }
        
        private void OnListarCompaniasOperationCompleted(object arg) {
            if ((this.ListarCompaniasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCompaniasCompleted(this, new ListarCompaniasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleado BuscarEmpleado(string cedula) {
            object[] results = this.Invoke("BuscarEmpleado", new object[] {
                        cedula});
            return ((Empleado)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEmpleadoAsync(string cedula) {
            this.BuscarEmpleadoAsync(cedula, null);
        }
        
        /// <remarks/>
        public void BuscarEmpleadoAsync(string cedula, object userState) {
            if ((this.BuscarEmpleadoOperationCompleted == null)) {
                this.BuscarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("BuscarEmpleado", new object[] {
                        cedula}, this.BuscarEmpleadoOperationCompleted, userState);
        }
        
        private void OnBuscarEmpleadoOperationCompleted(object arg) {
            if ((this.BuscarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEmpleadoCompleted(this, new BuscarEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarEmpleado(Empleado e) {
            this.Invoke("AgregarEmpleado", new object[] {
                        e});
        }
        
        /// <remarks/>
        public void AgregarEmpleadoAsync(Empleado e) {
            this.AgregarEmpleadoAsync(e, null);
        }
        
        /// <remarks/>
        public void AgregarEmpleadoAsync(Empleado e, object userState) {
            if ((this.AgregarEmpleadoOperationCompleted == null)) {
                this.AgregarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("AgregarEmpleado", new object[] {
                        e}, this.AgregarEmpleadoOperationCompleted, userState);
        }
        
        private void OnAgregarEmpleadoOperationCompleted(object arg) {
            if ((this.AgregarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarEmpleado(Empleado e) {
            this.Invoke("ModificarEmpleado", new object[] {
                        e});
        }
        
        /// <remarks/>
        public void ModificarEmpleadoAsync(Empleado e) {
            this.ModificarEmpleadoAsync(e, null);
        }
        
        /// <remarks/>
        public void ModificarEmpleadoAsync(Empleado e, object userState) {
            if ((this.ModificarEmpleadoOperationCompleted == null)) {
                this.ModificarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("ModificarEmpleado", new object[] {
                        e}, this.ModificarEmpleadoOperationCompleted, userState);
        }
        
        private void OnModificarEmpleadoOperationCompleted(object arg) {
            if ((this.ModificarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarEmpleado(Empleado e) {
            this.Invoke("EliminarEmpleado", new object[] {
                        e});
        }
        
        /// <remarks/>
        public void EliminarEmpleadoAsync(Empleado e) {
            this.EliminarEmpleadoAsync(e, null);
        }
        
        /// <remarks/>
        public void EliminarEmpleadoAsync(Empleado e, object userState) {
            if ((this.EliminarEmpleadoOperationCompleted == null)) {
                this.EliminarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("EliminarEmpleado", new object[] {
                        e}, this.EliminarEmpleadoOperationCompleted, userState);
        }
        
        private void OnEliminarEmpleadoOperationCompleted(object arg) {
            if ((this.EliminarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Logueo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleado Logueo(string cedula, string pass) {
            object[] results = this.Invoke("Logueo", new object[] {
                        cedula,
                        pass});
            return ((Empleado)(results[0]));
        }
        
        /// <remarks/>
        public void LogueoAsync(string cedula, string pass) {
            this.LogueoAsync(cedula, pass, null);
        }
        
        /// <remarks/>
        public void LogueoAsync(string cedula, string pass, object userState) {
            if ((this.LogueoOperationCompleted == null)) {
                this.LogueoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogueoOperationCompleted);
            }
            this.InvokeAsync("Logueo", new object[] {
                        cedula,
                        pass}, this.LogueoOperationCompleted, userState);
        }
        
        private void OnLogueoOperationCompleted(object arg) {
            if ((this.LogueoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogueoCompleted(this, new LogueoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarTerminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Terminal BuscarTerminal(string codigo) {
            object[] results = this.Invoke("BuscarTerminal", new object[] {
                        codigo});
            return ((Terminal)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarTerminalAsync(string codigo) {
            this.BuscarTerminalAsync(codigo, null);
        }
        
        /// <remarks/>
        public void BuscarTerminalAsync(string codigo, object userState) {
            if ((this.BuscarTerminalOperationCompleted == null)) {
                this.BuscarTerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarTerminalOperationCompleted);
            }
            this.InvokeAsync("BuscarTerminal", new object[] {
                        codigo}, this.BuscarTerminalOperationCompleted, userState);
        }
        
        private void OnBuscarTerminalOperationCompleted(object arg) {
            if ((this.BuscarTerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarTerminalCompleted(this, new BuscarTerminalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarTerminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarTerminal(Terminal t) {
            this.Invoke("AgregarTerminal", new object[] {
                        t});
        }
        
        /// <remarks/>
        public void AgregarTerminalAsync(Terminal t) {
            this.AgregarTerminalAsync(t, null);
        }
        
        /// <remarks/>
        public void AgregarTerminalAsync(Terminal t, object userState) {
            if ((this.AgregarTerminalOperationCompleted == null)) {
                this.AgregarTerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarTerminalOperationCompleted);
            }
            this.InvokeAsync("AgregarTerminal", new object[] {
                        t}, this.AgregarTerminalOperationCompleted, userState);
        }
        
        private void OnAgregarTerminalOperationCompleted(object arg) {
            if ((this.AgregarTerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarTerminalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarTerminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarTerminal(Terminal t) {
            this.Invoke("ModificarTerminal", new object[] {
                        t});
        }
        
        /// <remarks/>
        public void ModificarTerminalAsync(Terminal t) {
            this.ModificarTerminalAsync(t, null);
        }
        
        /// <remarks/>
        public void ModificarTerminalAsync(Terminal t, object userState) {
            if ((this.ModificarTerminalOperationCompleted == null)) {
                this.ModificarTerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarTerminalOperationCompleted);
            }
            this.InvokeAsync("ModificarTerminal", new object[] {
                        t}, this.ModificarTerminalOperationCompleted, userState);
        }
        
        private void OnModificarTerminalOperationCompleted(object arg) {
            if ((this.ModificarTerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarTerminalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarTerminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarTerminal(Terminal t) {
            this.Invoke("EliminarTerminal", new object[] {
                        t});
        }
        
        /// <remarks/>
        public void EliminarTerminalAsync(Terminal t) {
            this.EliminarTerminalAsync(t, null);
        }
        
        /// <remarks/>
        public void EliminarTerminalAsync(Terminal t, object userState) {
            if ((this.EliminarTerminalOperationCompleted == null)) {
                this.EliminarTerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarTerminalOperationCompleted);
            }
            this.InvokeAsync("EliminarTerminal", new object[] {
                        t}, this.EliminarTerminalOperationCompleted, userState);
        }
        
        private void OnEliminarTerminalOperationCompleted(object arg) {
            if ((this.EliminarTerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarTerminalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarTerminales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Terminal[] ListarTerminales() {
            object[] results = this.Invoke("ListarTerminales", new object[0]);
            return ((Terminal[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTerminalesAsync() {
            this.ListarTerminalesAsync(null);
        }
        
        /// <remarks/>
        public void ListarTerminalesAsync(object userState) {
            if ((this.ListarTerminalesOperationCompleted == null)) {
                this.ListarTerminalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTerminalesOperationCompleted);
            }
            this.InvokeAsync("ListarTerminales", new object[0], this.ListarTerminalesOperationCompleted, userState);
        }
        
        private void OnListarTerminalesOperationCompleted(object arg) {
            if ((this.ListarTerminalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTerminalesCompleted(this, new ListarTerminalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HerenciaInternacionales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ViajesInternacionales HerenciaInternacionales(ViajesInternacionales pViaje) {
            object[] results = this.Invoke("HerenciaInternacionales", new object[] {
                        pViaje});
            return ((ViajesInternacionales)(results[0]));
        }
        
        /// <remarks/>
        public void HerenciaInternacionalesAsync(ViajesInternacionales pViaje) {
            this.HerenciaInternacionalesAsync(pViaje, null);
        }
        
        /// <remarks/>
        public void HerenciaInternacionalesAsync(ViajesInternacionales pViaje, object userState) {
            if ((this.HerenciaInternacionalesOperationCompleted == null)) {
                this.HerenciaInternacionalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHerenciaInternacionalesOperationCompleted);
            }
            this.InvokeAsync("HerenciaInternacionales", new object[] {
                        pViaje}, this.HerenciaInternacionalesOperationCompleted, userState);
        }
        
        private void OnHerenciaInternacionalesOperationCompleted(object arg) {
            if ((this.HerenciaInternacionalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HerenciaInternacionalesCompleted(this, new HerenciaInternacionalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HerenciaNacionales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ViajesNacionales HerenciaNacionales(ViajesNacionales pViaje) {
            object[] results = this.Invoke("HerenciaNacionales", new object[] {
                        pViaje});
            return ((ViajesNacionales)(results[0]));
        }
        
        /// <remarks/>
        public void HerenciaNacionalesAsync(ViajesNacionales pViaje) {
            this.HerenciaNacionalesAsync(pViaje, null);
        }
        
        /// <remarks/>
        public void HerenciaNacionalesAsync(ViajesNacionales pViaje, object userState) {
            if ((this.HerenciaNacionalesOperationCompleted == null)) {
                this.HerenciaNacionalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHerenciaNacionalesOperationCompleted);
            }
            this.InvokeAsync("HerenciaNacionales", new object[] {
                        pViaje}, this.HerenciaNacionalesOperationCompleted, userState);
        }
        
        private void OnHerenciaNacionalesOperationCompleted(object arg) {
            if ((this.HerenciaNacionalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HerenciaNacionalesCompleted(this, new HerenciaNacionalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viaje BuscarViaje(int numero) {
            object[] results = this.Invoke("BuscarViaje", new object[] {
                        numero});
            return ((Viaje)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarViajeAsync(int numero) {
            this.BuscarViajeAsync(numero, null);
        }
        
        /// <remarks/>
        public void BuscarViajeAsync(int numero, object userState) {
            if ((this.BuscarViajeOperationCompleted == null)) {
                this.BuscarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarViajeOperationCompleted);
            }
            this.InvokeAsync("BuscarViaje", new object[] {
                        numero}, this.BuscarViajeOperationCompleted, userState);
        }
        
        private void OnBuscarViajeOperationCompleted(object arg) {
            if ((this.BuscarViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarViajeCompleted(this, new BuscarViajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarViaje(Viaje v) {
            this.Invoke("AgregarViaje", new object[] {
                        v});
        }
        
        /// <remarks/>
        public void AgregarViajeAsync(Viaje v) {
            this.AgregarViajeAsync(v, null);
        }
        
        /// <remarks/>
        public void AgregarViajeAsync(Viaje v, object userState) {
            if ((this.AgregarViajeOperationCompleted == null)) {
                this.AgregarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarViajeOperationCompleted);
            }
            this.InvokeAsync("AgregarViaje", new object[] {
                        v}, this.AgregarViajeOperationCompleted, userState);
        }
        
        private void OnAgregarViajeOperationCompleted(object arg) {
            if ((this.AgregarViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarViaje(Viaje v) {
            this.Invoke("ModificarViaje", new object[] {
                        v});
        }
        
        /// <remarks/>
        public void ModificarViajeAsync(Viaje v) {
            this.ModificarViajeAsync(v, null);
        }
        
        /// <remarks/>
        public void ModificarViajeAsync(Viaje v, object userState) {
            if ((this.ModificarViajeOperationCompleted == null)) {
                this.ModificarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarViajeOperationCompleted);
            }
            this.InvokeAsync("ModificarViaje", new object[] {
                        v}, this.ModificarViajeOperationCompleted, userState);
        }
        
        private void OnModificarViajeOperationCompleted(object arg) {
            if ((this.ModificarViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarViaje(Viaje v) {
            this.Invoke("EliminarViaje", new object[] {
                        v});
        }
        
        /// <remarks/>
        public void EliminarViajeAsync(Viaje v) {
            this.EliminarViajeAsync(v, null);
        }
        
        /// <remarks/>
        public void EliminarViajeAsync(Viaje v, object userState) {
            if ((this.EliminarViajeOperationCompleted == null)) {
                this.EliminarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarViajeOperationCompleted);
            }
            this.InvokeAsync("EliminarViaje", new object[] {
                        v}, this.EliminarViajeOperationCompleted, userState);
        }
        
        private void OnEliminarViajeOperationCompleted(object arg) {
            if ((this.EliminarViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarViajes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viaje[] ListarViajes() {
            object[] results = this.Invoke("ListarViajes", new object[0]);
            return ((Viaje[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarViajesAsync() {
            this.ListarViajesAsync(null);
        }
        
        /// <remarks/>
        public void ListarViajesAsync(object userState) {
            if ((this.ListarViajesOperationCompleted == null)) {
                this.ListarViajesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarViajesOperationCompleted);
            }
            this.InvokeAsync("ListarViajes", new object[0], this.ListarViajesOperationCompleted, userState);
        }
        
        private void OnListarViajesOperationCompleted(object arg) {
            if ((this.ListarViajesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarViajesCompleted(this, new ListarViajesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ViajesXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ViajesXML() {
            object[] results = this.Invoke("ViajesXML", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ViajesXMLAsync() {
            this.ViajesXMLAsync(null);
        }
        
        /// <remarks/>
        public void ViajesXMLAsync(object userState) {
            if ((this.ViajesXMLOperationCompleted == null)) {
                this.ViajesXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViajesXMLOperationCompleted);
            }
            this.InvokeAsync("ViajesXML", new object[0], this.ViajesXMLOperationCompleted, userState);
        }
        
        private void OnViajesXMLOperationCompleted(object arg) {
            if ((this.ViajesXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViajesXMLCompleted(this, new ViajesXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Compania {
        
        private string _NombreField;
        
        private string _DireccionField;
        
        private string _TelefonoField;
        
        /// <remarks/>
        public string _Nombre {
            get {
                return this._NombreField;
            }
            set {
                this._NombreField = value;
            }
        }
        
        /// <remarks/>
        public string _Direccion {
            get {
                return this._DireccionField;
            }
            set {
                this._DireccionField = value;
            }
        }
        
        /// <remarks/>
        public string _Telefono {
            get {
                return this._TelefonoField;
            }
            set {
                this._TelefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ViajesNacionales))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ViajesInternacionales))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Viaje {
        
        private string _DestinoField;
        
        private int _NumViajeField;
        
        private Compania _ComField;
        
        private Terminal _TerField;
        
        private System.DateTime _FechaPartidaField;
        
        private System.DateTime _FechaArriboField;
        
        private int _CantidadAsientosField;
        
        private Empleado _EmpField;
        
        /// <remarks/>
        public string _Destino {
            get {
                return this._DestinoField;
            }
            set {
                this._DestinoField = value;
            }
        }
        
        /// <remarks/>
        public int _NumViaje {
            get {
                return this._NumViajeField;
            }
            set {
                this._NumViajeField = value;
            }
        }
        
        /// <remarks/>
        public Compania _Com {
            get {
                return this._ComField;
            }
            set {
                this._ComField = value;
            }
        }
        
        /// <remarks/>
        public Terminal _Ter {
            get {
                return this._TerField;
            }
            set {
                this._TerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime _FechaPartida {
            get {
                return this._FechaPartidaField;
            }
            set {
                this._FechaPartidaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime _FechaArribo {
            get {
                return this._FechaArriboField;
            }
            set {
                this._FechaArriboField = value;
            }
        }
        
        /// <remarks/>
        public int _CantidadAsientos {
            get {
                return this._CantidadAsientosField;
            }
            set {
                this._CantidadAsientosField = value;
            }
        }
        
        /// <remarks/>
        public Empleado _Emp {
            get {
                return this._EmpField;
            }
            set {
                this._EmpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Terminal {
        
        private string _CodigoField;
        
        private string _CiudadField;
        
        private string _PaisField;
        
        private string[] _FacilidadesField;
        
        /// <remarks/>
        public string _Codigo {
            get {
                return this._CodigoField;
            }
            set {
                this._CodigoField = value;
            }
        }
        
        /// <remarks/>
        public string _Ciudad {
            get {
                return this._CiudadField;
            }
            set {
                this._CiudadField = value;
            }
        }
        
        /// <remarks/>
        public string _Pais {
            get {
                return this._PaisField;
            }
            set {
                this._PaisField = value;
            }
        }
        
        /// <remarks/>
        public string[] _Facilidades {
            get {
                return this._FacilidadesField;
            }
            set {
                this._FacilidadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empleado {
        
        private string _CedulaField;
        
        private string _ContraseñaField;
        
        private string _NombreCompletoField;
        
        /// <remarks/>
        public string _Cedula {
            get {
                return this._CedulaField;
            }
            set {
                this._CedulaField = value;
            }
        }
        
        /// <remarks/>
        public string _Contraseña {
            get {
                return this._ContraseñaField;
            }
            set {
                this._ContraseñaField = value;
            }
        }
        
        /// <remarks/>
        public string _NombreCompleto {
            get {
                return this._NombreCompletoField;
            }
            set {
                this._NombreCompletoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ViajesNacionales : Viaje {
        
        private int _ParadasIntermediasField;
        
        /// <remarks/>
        public int _ParadasIntermedias {
            get {
                return this._ParadasIntermediasField;
            }
            set {
                this._ParadasIntermediasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ViajesInternacionales : Viaje {
        
        private bool _ServicioBordoField;
        
        private string _DocumentacionField;
        
        /// <remarks/>
        public bool _ServicioBordo {
            get {
                return this._ServicioBordoField;
            }
            set {
                this._ServicioBordoField = value;
            }
        }
        
        /// <remarks/>
        public string _Documentacion {
            get {
                return this._DocumentacionField;
            }
            set {
                this._DocumentacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarCompaniaCompletedEventHandler(object sender, BuscarCompaniaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarCompaniaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarCompaniaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Compania Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Compania)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AgregarCompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ModificarCompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void EliminarCompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarCompaniasCompletedEventHandler(object sender, ListarCompaniasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCompaniasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCompaniasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Compania[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Compania[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarEmpleadoCompletedEventHandler(object sender, BuscarEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AgregarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ModificarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void EliminarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void LogueoCompletedEventHandler(object sender, LogueoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogueoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogueoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarTerminalCompletedEventHandler(object sender, BuscarTerminalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarTerminalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarTerminalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Terminal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Terminal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AgregarTerminalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ModificarTerminalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void EliminarTerminalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarTerminalesCompletedEventHandler(object sender, ListarTerminalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTerminalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTerminalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Terminal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Terminal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void HerenciaInternacionalesCompletedEventHandler(object sender, HerenciaInternacionalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HerenciaInternacionalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HerenciaInternacionalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ViajesInternacionales Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ViajesInternacionales)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void HerenciaNacionalesCompletedEventHandler(object sender, HerenciaNacionalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HerenciaNacionalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HerenciaNacionalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ViajesNacionales Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ViajesNacionales)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarViajeCompletedEventHandler(object sender, BuscarViajeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarViajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarViajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viaje Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viaje)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AgregarViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ModificarViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void EliminarViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarViajesCompletedEventHandler(object sender, ListarViajesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarViajesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarViajesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viaje[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viaje[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ViajesXMLCompletedEventHandler(object sender, ViajesXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViajesXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViajesXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591